### ISSUE TITLE
remove spaces in model names

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [pete-hulson/goa_pop#3]
https://github.com/pete-hulson/goa_pop/tree/main/2023/models

@pete-hulson strongly discourage spaces in any names would be better to do something like 2020.1-2021, 2020.1-2023 and add to the readme that model names are model year.id-data_year 
bonus that this can be filtered & sorted more easily

also instead of using "models" it may be worth considering 'research' and 'mgmt' as separate folders to follow the diff tracks

**Comment by pete-hulson** [comment]
yup, changed the model names and folder convention
